# Generated by Django 4.2.16 on 2024-11-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfiles',
            old_name='cover',
            new_name='file_data',
        ),
    ]
